version: "3.5"
services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - ./html:/var/www/html
      - ./tmp:/tmp
      - ./logs/php:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file: .env
    networks:
      - bridge-network

  web:
    image: nginx:1.17-alpine
    container_name: httpd
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./tmp:/tmp
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge-network

  db:
    image: postgres:9.6
    container_name: db
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:rw
      - ./postgres_init/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - bridge-network

networks:
  default:
    external:
      name: bridge
  bridge-network:
    name: container-link
    driver: bridge

volumes:
  postgres-data-volume:
    name: postgres-data
    driver: local
